runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"
- name: django
  version: "1.4"
- name: pycrypto
  version: latest

env_variables:
    CLOUDSQL_CONNECTION_NAME: "cryptography-176921:us-central1:cryptography"
    CLOUDSQL_USER: "amin"
    CLOUDSQL_PASSWORD: "amin123"
    CLOUDSQL_DATABASE: "cryptography"
