runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /.*
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"
- name: django
  version: "1.4"
- name: pycrypto
  version: latest

env_variables:
    CLOUDSQL_CONNECTION_NAME: "your database name"
    CLOUDSQL_USER: "your username"
    CLOUDSQL_PASSWORD: "your password"
    CLOUDSQL_DATABASE: "database name"
